// Generated by CoffeeScript 1.6.2
var $;

$ = jQuery;

$.fn.extend({
  simpletree: function() {
    var attach;

    attach = function(el) {
      return el.delegate("ul.parent > li .toggle", "click", function(e) {
        e.preventDefault();
        $(this).parent().find("ul.child").first().slideToggle({
          duration: 100
        });
        if ($(this).hasClass("closed")) {
          return $(this).removeClass("closed");
        } else {
          return $(this).addClass("closed");
        }
      });
    };
    return attach(this);
  }
});
